### PR TITLE
Initialize ida-minsc's subsystems for earlier versions of IDA (< 6.95) where not all hooks are available

### PR DESCRIPTION
**Pull request by arizvisa**
IDAPython for versions of IDA prior to 6.95 don't expose all the hooks/notifications that are required to initialize minsc's subsystems. This happens when populating the root namespace at startup.

This PR approaches the solution to this issue via two methods. First, the order of the version checking for hooks are inverted so that the newer versions of IDA gets priority which slightly increases performance (despite initialization performance being unimportant.).

The second thing that's done is that we use the IDA version to determine what hooks are available and use them when possible. As there will be situations where we'll be unable to use information about the database chosen by the user (due to not knowing the processor module or loader), we'll be forced to choose reasonable defaults when initializing minsc or we'll need to allow the user (through some means) to influence those particular options. 

As I don't have a version of IDA 6.8 handy (but I was able to get the SDK for it), this will unfortunately be developed blindly.

This aims to close issue #46.

### CODE REVIEW

**Comment by arizvisa** [comment]
This PR includes a large number of commits as a couple of things were done.

First of all, the logic for IDA's hooking interfaces were split up using a base class under `base/_interface.py`. Doing this allows usage of the same interface to hook both notifications and `IDP_Hooks`, `IDB_Hooks`, and `UI_Hooks` multiple times using the same interface.

Next, the hooks were moved from the `__root__.py` file (which controls the default namespace for IDA-minsc) under the `misc/hooks.py` file.

The last thing that was done was that the IDA version is checked in order to distinguish which hooks are available. If a particular hook isn't available, then that hook is simulated using IDA's notification api (which was wrapped with the `prioritynotification` interface).

Hopefully this cleans up the hooks so it's a little bit more readable and hence more maintainable

**Comment by gool123456** [comment]
> This PR includes a large number of commits as a couple of things were done.
> 
> First of all, the logic for IDA's hooking interfaces were split up using a base class under `base/_interface.py`. Doing this allows usage of the same interface to hook both notifications and `IDP_Hooks`, `IDB_Hooks`, and `UI_Hooks` multiple times using the same interface.
> 
> Next, the hooks were moved from the `__root__.py` file (which controls the default namespace for IDA-minsc) under the `misc/hooks.py` file.
> 
> The last thing that was done was that the IDA version is checked in order to distinguish which hooks are available. If a particular hook isn't available, then that hook is simulated using IDA's notification api (which was wrapped with the `prioritynotification` interface).
> 
> Hopefully this cleans up the hooks so it's a little bit more readable and hence more maintainable


Thank you very much for reminding me, please forgive me that I do n’t know how to use GitHub ..
 I did n’t know that GitHub can choose a branch to download directly, 
all are changed by Pull requests. 
Then download the latest GH-46 package, ida 6.8 These errors are shown:

```
WARNING: root: Unable to add notification for idaapi.NW_INITIDA (4). Setting up hooks manually ...
internal.interface.prioritynotification.add (0x1, <bound method classobj .__ nw_newprc__ of <class interface.typemap at 0x053E0EA0 >>, priority = 10): Unable to connect to the specified notification (0x1).
Traceback (most recent call last):
  File "D: \ tools \ IDA_Pro_v6.8_and_Hex-Rays_Decompiler_ (ARM, x64, x86) _Hskyre \ python \ idaapi.py", line 641, in IDAPython_ExecScript
    execfile (script, g)
  File "C: \ Users \ Hskyre \ AppData \ Roaming \ Hex-Rays \ IDA Pro \ idapythonrc.py", line 198, in <module>
    __root__ = imp.load_source ('__ root__', os.path.join (root, '__root__.py'))
  File "C: \ Users \ Hskyre \ AppData \ Roaming \ Hex-Rays \ IDA Pro \ __ root__.py", line 113, in <module>
    __import __ ('hooks'). make_ida_not_suck_cocks (idaapi.NW_INITIDA)
  File "C: \ Users \ Hskyre \ AppData \ Roaming \ Hex-Rays \ IDA Pro \ misc \ hooks.py", line 747, in make_ida_not_suck_cocks
    idaapi .__ notification __. add (idaapi.NW_OPENIDB, interface.typemap .__ nw_newprc__, 10)
  File "C: \ Users \ Hskyre \ AppData \ Roaming \ Hex-Rays \ IDA Pro \ base \ _interface.py", line 312, in add
    raise NameError (u "{: s} .add ({: # x}, {! r}, priority = {: d}): Unable to connect to the specified {: s}.". format ('.'. join (('internal', __name__, cls .__ name__)), target, callable, priority, self .__ formatter __ (target)))
NameError: internal.interface.prioritynotification.add (0x1, <bound method classobj .__ nw_newprc__ of <class interface.typemap at 0x053E0EA0 >>, priority = 10): Unable to connect to the specified notification (0x1).
```

Then I executed the output, showing : 

```
Python> print dir (idaapi.IDB_Hooks)
['__class__', '__del__', '__delattr__', '__dict__', '__disown__', '__doc__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', ' __reduce__ ',' __reduce_ex__ ',' __repr__ ',' __setattr__ ',' __sizeof__ ',' __str__ ',' __subclasshook__ ',' __swig_destroy__ ',' area_um_cmt'cm_cmt , 'enum_cmt_changed', 'enum_created', 'enum_deleted', 'enum_member_created', 'enum_member_deleted', 'enum_renamed', 'func_noret_changed', 'func_tail_appended', 'func_tail_removed', '_op _,' op segm_added ',' segm_deleted ',' segm_end_changed ',' segm_moved ',' segm_start_changed ',' struc_cmt_changed ',' struc_created ',' struc_deleted ',' struc_expanded ',' struc_member_de __'_''_ ' , 'struc_renamed', 'tail_owner_changed', 'thisown', 'thunk_func_created', 'ti_changed', 'unhook']
Python> print dir (idaapi.IDP_Hooks)
['__class__', '__del__', '__delattr__', '__dict__', '__disown__', '__doc__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', ' __reduce__ ',' __reduce_ex__ ',' __repr__ ',' __setattr__ ',' __sizeof__ ',' __str__ ',' __subclasshook__ ',' __swig_destroy__ ',' __weakref__ ',' add_y''auto ', , 'auto_queue_empty', 'closebase', 'custom_ana', 'custom_emu', 'custom_mnem', 'custom_out', 'custom_outop', 'del_func', 'hook', 'is_call_insn', 'is_ret_insn', 'is_sane_insn', ' load_idasgn ',' make_code ',' make_data ',' may_be_func ',' rename ',' renamed ',' savebase ',' thisown ',' undefine ',' unhook ']
Python> print dir (idaapi.UI_Hooks)
['__class__', '__del__', '__delattr__', '__dict__', '__disown__', '__doc__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', ' __reduce__ ',' __reduce_ex__ ',' __repr__ ',' __setattr__ ',' __sizeof__ ',' __str__ ',' __subclasshook__ ',' __swig_destroy__ ',' current_t__form_fin_t_form_find , 'populating_tform_popup', 'postprocess', 'preprocess', 'saved', 'saving', 'term', 'thisown', 'unhook', 'updated_actions', 'updating_actions']
```

I really admire you, you can write so much code without the support of ida6.8.

**Comment by arizvisa** [comment]
> > This PR includes a large number of commits as a couple of things were done.
> > First of all, the logic for IDA's hooking interfaces were split up using a base class under `base/_interface.py`. Doing this allows usage of the same interface to hook both notifications and `IDP_Hooks`, `IDB_Hooks`, and `UI_Hooks` multiple times using the same interface.
> > Next, the hooks were moved from the `__root__.py` file (which controls the default namespace for IDA-minsc) under the `misc/hooks.py` file.
> > The last thing that was done was that the IDA version is checked in order to distinguish which hooks are available. If a particular hook isn't available, then that hook is simulated using IDA's notification api (which was wrapped with the `prioritynotification` interface).
> > Hopefully this cleans up the hooks so it's a little bit more readable and hence more maintainable
> 
> Thank you very much for reminding me, please forgive me that I do n’t know how to use GitHub ..
> I did n’t know that GitHub can choose a branch to download directly,
> all are changed by Pull requests.
> Then download the latest [GH-46](https://github.com/arizvisa/ida-minsc/issues/46) package, ida 6.8 These errors are shown:

No worries. All is forgiven. :)

> ```
> WARNING: root: Unable to add notification for idaapi.NW_INITIDA (4). Setting up hooks manually ...
> internal.interface.prioritynotification.add (0x1, <bound method classobj .__ nw_newprc__ of <class interface.typemap at 0x053E0EA0 >>, priority = 10): Unable to connect to the specified notification (0x1).
> Traceback (most recent call last):
>   File "D: \ tools \ IDA_Pro_v6.8_and_Hex-Rays_Decompiler_ (ARM, x64, x86) _Hskyre \ python \ idaapi.py", line 641, in IDAPython_ExecScript
>     execfile (script, g)
>   File "C: \ Users \ Hskyre \ AppData \ Roaming \ Hex-Rays \ IDA Pro \ idapythonrc.py", line 198, in <module>
>     __root__ = imp.load_source ('__ root__', os.path.join (root, '__root__.py'))
>   File "C: \ Users \ Hskyre \ AppData \ Roaming \ Hex-Rays \ IDA Pro \ __ root__.py", line 113, in <module>
>     __import __ ('hooks'). make_ida_not_suck_cocks (idaapi.NW_INITIDA)
>   File "C: \ Users \ Hskyre \ AppData \ Roaming \ Hex-Rays \ IDA Pro \ misc \ hooks.py", line 747, in make_ida_not_suck_cocks
>     idaapi .__ notification __. add (idaapi.NW_OPENIDB, interface.typemap .__ nw_newprc__, 10)
>   File "C: \ Users \ Hskyre \ AppData \ Roaming \ Hex-Rays \ IDA Pro \ base \ _interface.py", line 312, in add
>     raise NameError (u "{: s} .add ({: # x}, {! r}, priority = {: d}): Unable to connect to the specified {: s}.". format ('.'. join (('internal', __name__, cls .__ name__)), target, callable, priority, self .__ formatter __ (target)))
> NameError: internal.interface.prioritynotification.add (0x1, <bound method classobj .__ nw_newprc__ of <class interface.typemap at 0x053E0EA0 >>, priority = 10): Unable to connect to the specified notification (0x1).
> ```
 
Wow. Well that's very very lame. The first warnings for "NW_INITIDA", and "NW_TERMIDA" are for executing python when you "start IDA", or "terminate IDA". It's okay if these don't work, because we can assume that IDA has already started since we're already executing python.

However, that `NameError` exception that gets raised is for `NW_OPENIDB` which is intending to execute when you "open/create a database". Apparently notifications aren't working \_at all\_ in IDA 6.8, and I'll need to find some other place to hook in order to execute python whenever you open a database in order to auto-detect the processor. :-(

> Then I executed the output, showing :
> 
> ```
> Python> print dir (idaapi.IDB_Hooks)
> ['__class__', '__del__', '__delattr__', '__dict__', '__disown__', '__doc__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', ' __reduce__ ',' __reduce_ex__ ',' __repr__ ',' __setattr__ ',' __sizeof__ ',' __str__ ',' __subclasshook__ ',' __swig_destroy__ ',' area_um_cmt'cm_cmt , 'enum_cmt_changed', 'enum_created', 'enum_deleted', 'enum_member_created', 'enum_member_deleted', 'enum_renamed', 'func_noret_changed', 'func_tail_appended', 'func_tail_removed', '_op _,' op segm_added ',' segm_deleted ',' segm_end_changed ',' segm_moved ',' segm_start_changed ',' struc_cmt_changed ',' struc_created ',' struc_deleted ',' struc_expanded ',' struc_member_de __'_''_ ' , 'struc_renamed', 'tail_owner_changed', 'thisown', 'thunk_func_created', 'ti_changed', 'unhook']
> Python> print dir (idaapi.IDP_Hooks)
> ['__class__', '__del__', '__delattr__', '__dict__', '__disown__', '__doc__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', ' __reduce__ ',' __reduce_ex__ ',' __repr__ ',' __setattr__ ',' __sizeof__ ',' __str__ ',' __subclasshook__ ',' __swig_destroy__ ',' __weakref__ ',' add_y''auto ', , 'auto_queue_empty', 'closebase', 'custom_ana', 'custom_emu', 'custom_mnem', 'custom_out', 'custom_outop', 'del_func', 'hook', 'is_call_insn', 'is_ret_insn', 'is_sane_insn', ' load_idasgn ',' make_code ',' make_data ',' may_be_func ',' rename ',' renamed ',' savebase ',' thisown ',' undefine ',' unhook ']
> Python> print dir (idaapi.UI_Hooks)
> ['__class__', '__del__', '__delattr__', '__dict__', '__disown__', '__doc__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', ' __reduce__ ',' __reduce_ex__ ',' __repr__ ',' __setattr__ ',' __sizeof__ ',' __str__ ',' __subclasshook__ ',' __swig_destroy__ ',' current_t__form_fin_t_form_find , 'populating_tform_popup', 'postprocess', 'preprocess', 'saved', 'saving', 'term', 'thisown', 'unhook', 'updated_actions', 'updating_actions']
> ```

Thanks. I've been using the files at https://github.com/idapython/src/blob/build-1.7.2/swig/idp.i, to identify the hook points. But this output from you shows me what other places I can hook in order to execute python whenever you open a database.
 
> I really admire you, you can write so much code without the support of ida6.8.

Hah! I didn't do too much, I just moved some code around so that you can use the same interface to hook different parts of IDA, so it's not too much work.

I'll try and download IDA 6.8 from your Google Drive later today, I don't have reliable internet where I live at the moment and because of COVID-19 it takes me a bit to get into the library for wifi.

**Comment by arizvisa** [comment]
Oh, also.. @gool123456, is there something similar to GitHub that you use on your side of the world for hosting source code? After I figure out how to resolve your issue, I was thinking how cool it would be to host ida-minsc on the eastern side of the world too...

**Comment by arizvisa** [comment]
@gool123456, I've been trying to download that .rar from google drive and I can't seem to open it. I've downloaded it twice, with the sha256 being 0a167032e9c460aeca9fb3387fe4c73f01cca0a9c3129d9139de4062c2168422, but can't unrar it?
```
[1003] user@localhost ~$ sha256sum Downloads/IDA_Pro_v6.8_and_Hex-Rays_Decompiler_\(ARM\,x64\,x86\)_Green.rar 
0a167032e9c460aeca9fb3387fe4c73f01cca0a9c3129d9139de4062c2168422  Downloads/IDA_Pro_v6.8_and_Hex-Rays_Decompiler_(ARM,x64,x86)_Green.rar
[1004] user@localhost ~$ sha256sum Downloads/IDA_Pro_v6.8_and_Hex-Rays_Decompiler_\(ARM\,x64\,x86\)_Green.rar 
0a167032e9c460aeca9fb3387fe4c73f01cca0a9c3129d9139de4062c2168422  Downloads/IDA_Pro_v6.8_and_Hex-Rays_Decompiler_(ARM,x64,x86)_Green.rar
[1004] user@localhost ~$ unrar l Downloads/IDA_Pro_v6.8_and_Hex-Rays_Decompiler_\(ARM\,x64\,x86\)_Green.rar 
l: Couldn't open archive. (Opening file failed.)
```

**Comment by gool123456** [comment]
Hi, What caused it ? :(  I downloaded it again, the hash256 value of the file is the same, and it is possible to use the latest winrar to decompress it. There is nothing wrong, you try to use the new Winrar to decompress it?
http://www.winrar.com.cn/
latest Winrar x64 Download:
http://www.winrar.com.cn/download-58064scp.html

> Hah! I didn't do too much, I just moved some code around so that you can use the same interface to hook different parts of IDA, so it's not too much work.
> 
> I'll try and download IDA 6.8 from your Google Drive later today, I don't have reliable internet where I live at the moment and because of COVID-19 it takes me a bit to get into the library for wifi.

Health first!  Where are you from?   I hope all COVID-19  of  leave the world sooner.

> Oh, also.. @gool123456, is there something similar to GitHub that you use on your side of the world for hosting source code? After I figure out how to resolve your issue, I was thinking how cool it would be to host ida-minsc on the eastern side of the world too...

I do n’t use GitHub-like stuff to host the source code, because I have n’t written great tools, tools like ida-minsc, maybe I will. You ’re cool. And software cracker .. and cracking COVID-19 humans. .. they are all so cool ..

**Comment by gool123456** [comment]
Have you used WeChat, I want to add you as a friend Ha! My id is : toosey

**Comment by arizvisa** [comment]
> Hi, What caused it ? :( I downloaded it again, the hash256 value of the file is the same, and it is possible to use the latest winrar to decompress it. There is nothing wrong, you try to use the new Winrar to decompress it?
> http://www.winrar.com.cn/
> latest Winrar x64 Download:
> http://www.winrar.com.cn/download-58064scp.html

Interesting...I didn't think 7zip, Ace, etc. wouldn't be able to interact with rar files. That's weird...I wonder if .rar is still changing as a file format...

> > Hah! I didn't do too much, I just moved some code around so that you can use the same interface to hook different parts of IDA, so it's not too much work.
> > I'll try and download IDA 6.8 from your Google Drive later today, I don't have reliable internet where I live at the moment and because of COVID-19 it takes me a bit to get into the library for wifi.
> 
> Health first! Where are you from? I hope all COVID-19 of leave the world sooner.

I'm in the USA.

> > Oh, also.. @gool123456, is there something similar to GitHub that you use on your side of the world for hosting source code? After I figure out how to resolve your issue, I was thinking how cool it would be to host ida-minsc on the eastern side of the world too...
> 
> I do n’t use GitHub-like stuff to host the source code, because I have n’t written great tools, tools like ida-minsc, maybe I will. You ’re cool. And software cracker .. and cracking COVID-19 humans. .. they are all so cool ..

Ah ok. I was thinking that there was perhaps something similar to github over where you're at.

**Comment by arizvisa** [comment]
> Have you used WeChat, I want to add you as a friend Ha! My id is : toosey

Nah. Unfortunately I don't use WeChat, I also don't have a reliable internet connection. :-/

However, I'm over on plurk.com. I think it's used by koreans.

**Comment by arizvisa** [comment]
@gool123456, So after testing this PR... It turns out that IDA 6.8 seems to execute Python prior to all of the notifications and hooking being available, so none of those APIs really work. Lol.

But, I was able to find a workaround by registering a timer using `idaapi.register_timer(...)`. It's set for 5 seconds. Although, I'm not sure if that's enough for everyone. Try synchronizing the PR and seeing if it works for you now.

One issue is that IDA 6.8 doesn't seem to let one hook comments, which means a big part of ida-minsc (the whole tagging infrastructure) doesn't work if you're using the user-interface. So to use tags, you'll need to manually type `database.tag(address, 'my-notes', 'blahblahblah')` or `func.tag(address, 'somenumber', 57005)`.

As a reminder, you can create a file in your home directory (`%USERPROFILE%`) called `.idapythonrc.py` which will execute on startup. Then to save typing you can put something like the following to alias stuff:

```
db = database
fn = function
h = database.here
tag = database.tag
ftag = function.tag
```

Anyways, once you sync. Let me know if it works for you. Thanks, good sir!

**Comment by gool123456** [comment]
@arizvisa  Great job, the newly modified one can run successfully on my ida.: Hah! With your help, I believe that I can prefer to write scripts. Thank you for your kind help. Good luck !!

**Comment by arizvisa** [comment]
Awesome. I'll work on merging this then. Thanks!

**Pull request merged**
